version: '3.8'

services:
  server:
    image: node:12-alpine
    ports:
    - 3000:3000
    command: npm run devStart

  authServer:
    image: node:12-alpine
    ports:
    - 4000:4000
    command: npm run devStartAuth


